
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_COUNT_PRODUCT = 'UPDATE_COUNT_PRODUCT';
export const GET_ALL_BASKET_PRODUCTS="GET_ALL_BASKET_PRODUCTS"
export const GET_ALL_FAVORITES_PRODUCTS="GET_ALL_FAVORITES_PRODUCTS"
export const ADD_FAVORITE_PRODUCT="ADD_FAVORITE_PRODUCT"
export const DELETE_FAVORITE_PRODUCT="DELETE_FAVORITE_PRODUCT"
